### ISSUE TITLE
[BUG] toshy fails to install the services

### ISSUE THREAD

**Issue by fiveNinePlusR** [RedBearAK/Toshy#719]
```
(CG) Toshy config sees this environment:
        DISTRO_ID        = 'cachyos'
        DISTRO_VER       = 'notfound'
        VARIANT_ID       = 'notfound'
        SESSION_TYPE     = 'wayland'
        DESKTOP_ENV      = 'kde'
        DE_MAJ_VER       = '6'
        WINDOW_MGR       = 'kwin_wayland'

(DD) ENVIRON API: 
        Session type     = 'wayland'
        Window manager   = 'kwin_wayland'


Keyboard type (Apple, Chromebook, IBM, Windows): 
Keyboard device name (try 'toshy-devices'): 

(DD) KBTYPE: 'Apple' | (CACHED) Type in dev name: 'Apple Inc. Apple Keyboard'

Bare metal or virtual machine: Bare metal 
```

* * *

Problem observed:

Re-installed toshy per the instructions to see why it wouldn't start up and the services do not get installed correctly. I removed the config folder in ~/.config/toshy to get a clean config.

runs from the terminal in toshy-debug mode but the services are broken. any ideas? 

diagnostic info: 

[toshy-diagnostics.txt](https://github.com/user-attachments/files/22584055/toshy-diagnostics.txt)

**Comment by RedBearAK** [comment]
@fiveNinePlusR 

I thought maybe this was related to issue #701, but you would have had to have downloaded from a "release" and used Ark to extract the zip files, breaking the symlinks that used to be there. If you used the one-liner command or downloaded from the green button on the main repo page, that issue was fixed. Anyway this seems a bit different. But can you describe the exact install steps you're using? 

What happens if you run this command in the terminal? This should get to the heart of the matter without needing to see the whole installer logging. 

```
toshy-systemd-setup
```

That command should do the same thing the installer script does, to attempt to install the systemd user services. You don't use "sudo" with this, since it installs "user" services, not "system" services. It will first try to remove any existing services, and then try to install fresh service unit files and enable/start them. 

> I removed the config folder in ~/.config/toshy to get a clean config.

This is unnecessary, the installer makes a new folder each time, while keeping your keymapper config file and preferences file in a backup folder and merging them into the new fresh folder.

**Comment by fiveNinePlusR** [comment]
> I thought maybe this was related to issue https://github.com/RedBearAK/Toshy/issues/701, but you would have had to have downloaded from a "release" and used Ark to extract the zip files, breaking the symlinks that used to be there. If you used the one-liner command or downloaded from the green button on the main repo page, that issue was fixed. Anyway this seems a bit different. But can you describe the exact install steps you're using?

installed via the oneliner command and can confirm that the #701 is not applicable as the scripts are actual text files and named correctly. 

it is still broken but i was able to restore the symlinks and they point to the outer `~/.config/systemd/user/toshy-*` services.

<img width="955" height="597" alt="Image" src="https://github.com/user-attachments/assets/1c6ec775-10e8-42b5-b490-f256acb95d0b" />

It could be a "me" issue as i was installing some other service for a server process in the `etc` systemd folder and may have messed something up but i'm not sure... but if you have any thoughts I'd love to hear them. the screenshot above shows that i am also having trouble enabling the ssh-agent service and has an odd path. maybe that's a clue?

**Comment by fiveNinePlusR** [comment]
also here's the output of the command you wanted 

```
toshy-systemd-setup

Setting up Toshy service unit files in '/home/username/.config/systemd/user'...

Removing Toshy systemd services...


Finished removing Toshy systemd services.


Issuing systemctl daemon-reload...

Starting Toshy systemd services...
Failed to reenable unit: Unit toshy-cosmic-dbus.service does not exist
Failed to start toshy-cosmic-dbus.service: Unit toshy-cosmic-dbus.service not found.
Failed to reenable unit: Unit toshy-kwin-dbus.service does not exist
Failed to start toshy-kwin-dbus.service: Unit toshy-kwin-dbus.service not found.
Failed to reenable unit: Unit toshy-wlroots-dbus.service does not exist
Failed to start toshy-wlroots-dbus.service: Unit toshy-wlroots-dbus.service not found.
Failed to reenable unit: Unit toshy-config.service does not exist
Failed to start toshy-config.service: Unit toshy-config.service not found.
Failed to reenable unit: Unit toshy-session-monitor.service does not exist
Failed to start toshy-session-monitor.service: Unit toshy-session-monitor.service not found.

Displaying status of Toshy systemd services...

Unit toshy-cosmic-dbus.service could not be found.

Unit toshy-kwin-dbus.service could not be found.

Unit toshy-wlroots-dbus.service could not be found.

Unit toshy-session-monitor.service could not be found.

Unit toshy-config.service could not be found.

Finished installing Toshy systemd services.

```

**Comment by RedBearAK** [comment]
@fiveNinePlusR 

I see that my service setup script is not as verbose as it should be, regarding the service unit install process and possible failures in the copying. I'll have to fix that. 

So at the moment I have no idea what's going on. When you put the unit files and symlinks into place and ran daemon-reload, that should have been enough to get it working. But the symlinks are normally automatically put in place when "enabling" the service units sitting in the main systemd-user folder. 

For things named "socket", my limited understanding is that they are meant to be activated by something, not quite like "service" units. But there are a lot of quirks with systemd services that I don't understand. 

Until I can edit the systemd setup script to give it some more verbose output and perhaps more robust debugging output, I don't have a clue what the problem is. It's not something I've ever encountered in testing, but that doesn't necessarily mean it's just a "you" problem. Things often change in Linux and just suddenly break things. 

For now you'll just have to run Toshy manually, which is something anyone on a distro without systemd has to do anyway, and there is no harm in doing that long term. Just dedicated a terminal tab to keep it running. I'll get back to you when I can update the systemd setup script or have some other idea. 

I've tested CachyOS before, it was just another Arch distro type. Is this an immutable variant or anything like that? Unusual permissions on the services folder? 

I have no other ideas at the moment.

**Comment by fiveNinePlusR** [comment]
> For things named "socket", my limited understanding is that they are meant to be activated by something, not quite like "service" units. But there are a lot of quirks with systemd services that I don't understand.

yeah that makes sense. the issue happens identically with the `arch-update-tray.service` too so maybe it's just broken somehow. 

> I've tested CachyOS before, it was just another Arch distro type. Is this an immutable variant or anything like that? Unusual permissions on the services folder?

yeah it's just arch with a few performance things added. not immutable or anything like that. I just checked the services and it's 755. 

I'll just run it in a terminal tab for now until i can figure it out or get something else to try from you then. thanks again!

**Comment by RedBearAK** [comment]
Here's a version of the services setup script with significantly increased debugging output. This will be in future versions of Toshy as a troubleshooting option, but right now it would only be in the "dev_beta" branch. Instead of reinstalling Toshy, it's just as easy to download the script here and run it in a terminal. Should run from anywhere with no issue, since it knows all the paths it needs. 

[toshy-systemd-setup-debug.sh](https://github.com/user-attachments/files/22694303/toshy-systemd-setup-debug.sh)

Mark it as executable or just run it like this:
```sh
bash ./toshy-systemd-setup-debug.sh
```

Let's see what it might reveal about what the actual problem is.

**Comment by fiveNinePlusR** [comment]
Thanks for that script! Here's the output of running it:

Not sure what's going wrong as all the paths look correct. I do think this is somehow systemd userspace being broken somehow for me. (the sudo version of systemctl without --user works fine.)

```
❯❯❯ ./toshy-systemd-setup-debug.sh
[INFO] Running as user: fivenineplusr
[INFO] Home directory: /home/fivenineplusr
[SUCCESS] systemctl command found
[INFO] Systemd version: systemd 258 (258-4-arch)
[INFO] Checking if systemd user services are supported...
[SUCCESS] Systemd user services are supported
[INFO] XDG_RUNTIME_DIR is set to: /run/user/1000
[SUCCESS] XDG_RUNTIME_DIR exists and is accessible
[INFO] Configuration paths:
[INFO]   LOCAL_BIN_PATH: /home/fivenineplusr/.local/bin
[INFO]   USER_SYSD_PATH: /home/fivenineplusr/.config/systemd/user
[INFO]   TOSHY_CFG_PATH: /home/fivenineplusr/.config/toshy
[INFO]   SYSD_UNIT_PATH: /home/fivenineplusr/.config/toshy/systemd-user-service-units

================================================================================
[INFO] Setting up Toshy service unit files in '/home/fivenineplusr/.config/systemd/user'...
================================================================================

[INFO] Creating necessary directories...
[SUCCESS] Creating systemd user directory
[SUCCESS] Creating autostart directory
[SUCCESS] Source directory exists: /home/fivenineplusr/.config/toshy/systemd-user-service-units
[INFO] Checking for source service files...
[SUCCESS]   Found: toshy-cosmic-dbus.service
[SUCCESS]   Found: toshy-kwin-dbus.service
[SUCCESS]   Found: toshy-wlroots-dbus.service
[SUCCESS]   Found: toshy-config.service
[SUCCESS]   Found: toshy-session-monitor.service
[SUCCESS] Desktop entry file exists: /home/fivenineplusr/.config/toshy/desktop/Toshy_Import_Vars.desktop

[INFO] Removing any existing Toshy systemd services...
[INFO] Running: /home/fivenineplusr/.local/bin/toshy-systemd-remove

Removing Toshy systemd services...


Finished removing Toshy systemd services.

[SUCCESS] Removal script completed successfully

[INFO] Copying service files to systemd user directory...
[INFO]   Copying: toshy-cosmic-dbus.service
[SUCCESS]     cp toshy-cosmic-dbus.service
[SUCCESS]     Verified: file exists at destination
[INFO]   Copying: toshy-kwin-dbus.service
[SUCCESS]     cp toshy-kwin-dbus.service
[SUCCESS]     Verified: file exists at destination
[INFO]   Copying: toshy-wlroots-dbus.service
[SUCCESS]     cp toshy-wlroots-dbus.service
[SUCCESS]     Verified: file exists at destination
[INFO]   Copying: toshy-config.service
[SUCCESS]     cp toshy-config.service
[SUCCESS]     Verified: file exists at destination
[INFO]   Copying: toshy-session-monitor.service
[SUCCESS]     cp toshy-session-monitor.service
[SUCCESS]     Verified: file exists at destination
[INFO] Copying desktop entry file...
[SUCCESS]   cp Toshy_Import_Vars.desktop

[INFO] Importing environment variables for systemd user services...
[INFO] Current environment values:
[INFO]   KDE_SESSION_VERSION=6
[INFO]   XDG_SESSION_TYPE=wayland
[INFO]   XDG_SESSION_DESKTOP=KDE
[INFO]   XDG_CURRENT_DESKTOP=KDE
[INFO]   DESKTOP_SESSION=plasma
[INFO]   DISPLAY=:0
[INFO]   WAYLAND_DISPLAY=wayland-0
[INFO] Running: systemctl --user import-environment...
[SUCCESS] Environment variables imported successfully

[INFO] Reloading systemd user daemon...
[SUCCESS] systemctl --user daemon-reload

[INFO] Enabling and starting Toshy systemd services...

--------------------------------------------------------------------------------
[INFO] Processing: toshy-cosmic-dbus.service
[INFO]   Running: systemctl --user reenable toshy-cosmic-dbus.service
[ERROR]   reenable failed with exit code: 1
[INFO]     Failed to reenable unit: Unit toshy-cosmic-dbus.service does not exist
[INFO]   Running: systemctl --user start toshy-cosmic-dbus.service
[ERROR]   start failed with exit code: 5
[INFO]     Failed to start toshy-cosmic-dbus.service: Unit toshy-cosmic-dbus.service not found.
[ERROR]   Verification failed: service is NOT enabled
[WARNING]   Service is not active/running
--------------------------------------------------------------------------------
[INFO] Processing: toshy-kwin-dbus.service
[INFO]   Running: systemctl --user reenable toshy-kwin-dbus.service
[ERROR]   reenable failed with exit code: 1
[INFO]     Failed to reenable unit: Unit toshy-kwin-dbus.service does not exist
[INFO]   Running: systemctl --user start toshy-kwin-dbus.service
[ERROR]   start failed with exit code: 5
[INFO]     Failed to start toshy-kwin-dbus.service: Unit toshy-kwin-dbus.service not found.
[ERROR]   Verification failed: service is NOT enabled
[WARNING]   Service is not active/running
--------------------------------------------------------------------------------
[INFO] Processing: toshy-wlroots-dbus.service
[INFO]   Running: systemctl --user reenable toshy-wlroots-dbus.service
[ERROR]   reenable failed with exit code: 1
[INFO]     Failed to reenable unit: Unit toshy-wlroots-dbus.service does not exist
[INFO]   Running: systemctl --user start toshy-wlroots-dbus.service
[ERROR]   start failed with exit code: 5
[INFO]     Failed to start toshy-wlroots-dbus.service: Unit toshy-wlroots-dbus.service not found.
[ERROR]   Verification failed: service is NOT enabled
[WARNING]   Service is not active/running
--------------------------------------------------------------------------------
[INFO] Processing: toshy-config.service
[INFO]   Running: systemctl --user reenable toshy-config.service
[ERROR]   reenable failed with exit code: 1
[INFO]     Failed to reenable unit: Unit toshy-config.service does not exist
[INFO]   Running: systemctl --user start toshy-config.service
[ERROR]   start failed with exit code: 5
[INFO]     Failed to start toshy-config.service: Unit toshy-config.service not found.
[ERROR]   Verification failed: service is NOT enabled
[WARNING]   Service is not active/running
--------------------------------------------------------------------------------
[INFO] Processing: toshy-session-monitor.service
[INFO]   Running: systemctl --user reenable toshy-session-monitor.service
[ERROR]   reenable failed with exit code: 1
[INFO]     Failed to reenable unit: Unit toshy-session-monitor.service does not exist
[INFO]   Running: systemctl --user start toshy-session-monitor.service
[ERROR]   start failed with exit code: 5
[INFO]     Failed to start toshy-session-monitor.service: Unit toshy-session-monitor.service not found.
[ERROR]   Verification failed: service is NOT enabled
[WARNING]   Service is not active/running

================================================================================
[INFO] Displaying status of Toshy systemd services
================================================================================

--------------------------------------------------------------------------------
[INFO] Status of: toshy-cosmic-dbus.service
--------------------------------------------------------------------------------
Unit toshy-cosmic-dbus.service could not be found.

--------------------------------------------------------------------------------
[INFO] Status of: toshy-kwin-dbus.service
--------------------------------------------------------------------------------
Unit toshy-kwin-dbus.service could not be found.

--------------------------------------------------------------------------------
[INFO] Status of: toshy-wlroots-dbus.service
--------------------------------------------------------------------------------
Unit toshy-wlroots-dbus.service could not be found.

--------------------------------------------------------------------------------
[INFO] Status of: toshy-config.service
--------------------------------------------------------------------------------
Unit toshy-config.service could not be found.

--------------------------------------------------------------------------------
[INFO] Status of: toshy-session-monitor.service
--------------------------------------------------------------------------------
Unit toshy-session-monitor.service could not be found.


================================================================================
[INFO] Installation Summary
================================================================================

Services enabled: 0 / 5
Services running: 0 / 5

Errors encountered: 15
Warnings encountered: 5

[ERROR] Some services failed to enable. Check error messages above.

[INFO] For more details, you can run:
[INFO]   toshy-services-status
[INFO]   journalctl --user -xeu <service-name>
```

**Comment by RedBearAK** [comment]
This should reveal whether that folder is in the paths that systemd looks in for the unit files:

```
systemctl --user show --property=UnitPath | sed -e 's/ /\n/g' | grep -i home
```

For me on Fedora 41 this shows a couple of home folder locations:

```
systemctl --user show --property=UnitPath | sed -e 's/ /\n/g' | grep -i home
UnitPath=/home/kris/.config/systemd/user.control
/home/kris/.config/systemd/user
/home/kris/.local/share/systemd/user
```

If your `/home/fivenineplusr/.config/systemd/user` location is not in the list, that would explain why the services can't be found. But why that might happen or how to fix it is beyond me. 

Also check the value of this environment variable:

```
echo $XDG_CONFIG_HOME
```

It's not set on my system, but maybe yours is set to something other than `~/.config`. 

If you have "$HOME/.local/share/systemd/user" in the UnitPath list (and it works for you), I might think about switching over to using that instead of the config folder location.

**Comment by fiveNinePlusR** [comment]
Thanks for that diagnostic tidbit as it sent me down a good path to diagnose it! For some reason or another $HOME wasn't being respected early enough in the boot so i did a hack and put it in /etc/environment for now. now everything is working as it should. I do think it was just a weird issue that i had and not a more general problem with toshy. 

Thank you!

**Comment by RedBearAK** [comment]
@fiveNinePlusR 

>  I do think it was just a weird issue that i had and not a more general problem with toshy.

Until I see things going wrong in some testing, I will also have to assume that, for now. Good luck with finding the correct fix for your system.

**Comment by fiveNinePlusR** [comment]
I truly appreciate your help here. thank you so much and thank you for the great utility
